version: '3.7'
services:
    app:
        build: .
        container_name: imgforphp8
        volumes:
          - ./:/usr/share/nginx/html
        extra_hosts:
          - "host.docker.internal:host-gateway"
        ports:
          - 80:80
